### ISSUE TITLE
Need update to avoid dependency on 'impute'

### ISSUE THREAD

**Issue by zinagood** [SpitzerLab/statisticalScaffold#6]
Just tried installing, but ran into compatibility issue:
Error: Failed to install 'scaffold' from GitHub:
  (converted from warning) package ‘impute’ is not available (for R version 3.5.2)

Is it possible to avoid dependency on 'impute' package? Or any tip on avoiding this?

Thanks!
Zina

**Comment by mhspitzer** [comment]
Hi Zina,

Thanks for pointing this out. It looks like the impute package is now available on Bioconductor (https://www.bioconductor.org/packages/release/bioc/html/impute.html) instead of CRAN, so try installing it manually as a work around and let me know if that works. I'll need to update the dependencies.

Best,
Matt

**Comment by zinagood** [comment]
Thanks so much Matt!

I actually just figured it out and was about to close the 'Issue'.

It might be useful to add this note about installing 'impute' from
Bioconductor into installation instructions.

Hope you're doing well!
Zina
--
Zinaida Good
415-290-8944
